### ISSUE TITLE
two-way binding on panel state?

### ISSUE THREAD

**Issue by brenna** [adopted-ember-addons/ember-collapsible-panel#10]

**Comment by patric-eberle** [comment]
We also had a case, where it would have been helpful to get the panel state as a property. Without it we had to overwrite the on-click to handle state changes on our component.

**Comment by dirkdirk** [comment]
[See Issue #28](https://github.com/tedconf/ember-collapsible-panel/issues/28)

Edit `node_modules/ember-collapsible-panel/addon/components/cp-panel/template.hbs` like [this](https://github.com/tedconf/ember-collapsible-panel/blob/master/addon/components/cp-panel/template.hbs#L4).
