### ISSUE TITLE
Test cleanup for panel-actions state

### ISSUE THREAD

**Issue by samselikoff** [adopted-ember-addons/ember-collapsible-panel#13]
Need to add this in a test's `afterEach` for proper cleanup:

``` js
Ember.run(() => {
  application.__container__.lookup('service:panel-actions').get('state').reset();
});
```

Need a better solution

**Comment by MelSumner** [comment]
I'm going to close this issue merely due to age. If it's still an issue, please re-open. Thank you! 👍
