### ISSUE TITLE
Checkbox inside the panel header not working

### ISSUE THREAD

**Issue by onmondo** [adopted-ember-addons/ember-collapsible-panel#14]
The checkbox inside the panel header is not working.
I know that the panel header wraps any element in an <a> tag thus making the whole panel header a link.
Is there a way to include checkbox or any other element inside the header?

**Comment by samselikoff** [comment]
I can think of two ways to solve this. First would be to make your own header and put the link inside:

``` hbs
<div class="My-header">
  {{#cp-panel-toggle}}Toggle{{/cp-panel-toggle}}
  <input type="checkbox"> 
</div>
```

You could also add an anchor element within the header that doesn't bubble its action:

``` hbs
{{#cp-panel-toggle}}
  Title
  <input onclick={{action "toggleBar" bubbles=false}} checked={{bar}} type="checkbox">    
{{/cp-panel-toggle}}
```

That should trigger the other action without bubbling the event up to `cp-panel-toggle`'s click handler.

**Comment by onmondo** [comment]
I'll try your approach and notify you.

Thanks @samselikoff 

Appreciate your help :)

**Comment by onmondo** [comment]
Tried both the approach.

And solves the problem but the appearance is not going to be pretty.. but it works. Thanks @samselikoff
