### ISSUE TITLE
Uncaught TypeError: Cannot read property 'hasLiquidFire' of undefined dependency-checker.js:5 

### ISSUE THREAD

**Issue by cbou** [adopted-ember-addons/ember-collapsible-panel#19]
After installing this plugin I get an error from dependency-check.js.

**Comment by samselikoff** [comment]
What versions of ember/ember-cli are you on? Also, does your project's `package.json` have `ember-cli-dependency-checker` in its `devDependencies`?

I guess this assumes it's there but we should really make it part of this addon's dependencies.

**Comment by cbou** [comment]
I have ember 2.7.0 and ember-cli-dependency-checker ^1.2.0.

It's now fixed. It was an error on my project, my config/environment was wrong.

Thanks
