### ISSUE TITLE
Expose toggleIsOpen to parent component for ddau flow

### ISSUE THREAD

**Issue by RobIsHere** [adopted-ember-addons/ember-collapsible-panel#27]
What I would like to do:
- pass an action "toggleIsOpen" to the panel
- that action gets called
- I check if opening is allowed based on application state
- If ok, i set open=true

Is this possible? For now i hack something, but support for ddau pattern would be great!

Thanks for this add-on!

**Comment by dirkdirk** [comment]
These suggestions might help:

[See Issue #28](https://github.com/tedconf/ember-collapsible-panel/issues/28)

Edit `node_modules/ember-collapsible-panel/addon/components/cp-panel/template.hbs` like [this](https://github.com/tedconf/ember-collapsible-panel/blob/master/addon/components/cp-panel/template.hbs#L4).

This is possible:

````javascript
actions: {
    openPanel(panelName) {
      this.get('panelActions').open(panelName);
    },

    closePanel(panelName) {
      this.get('panelActions').close(panelName);
    },
````

**Comment by samselikoff** [comment]
@RobIsHere this is actually just not documented well, but the toggle component exposes an `on-click` action and the parent `panel` can take an `open` property.

```hbs
{{! application.hbs }}
{{#cp-panel open=open as |p|}}
  {{#p.toggle on-click=(action 'toggleOpen')}}
    <p>Click me!</p>
  {{/p.toggle}}

  {{#p.body}}
    <div>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nemo repellendus nisi asperiores esse aperiam aliquid nulla ad dolor autem neque, nihil inventore temporibus delectus earum facere corporis, quam ipsum maxime.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus neque magnam, hic quis beatae repellendus harum modi pariatur minus quidem alias! Eius incidunt impedit eaque, est, illo officiis expedita molestiae.</p>
    </div>
  {{/p.body}}
{{/cp-panel}}
```

```js
// controllers/application.js
import Ember from 'ember';

export default Ember.Controller.extend({

  open: true,

  actions: {
    toggleOpen() {
      this.toggleProperty('open');
    }
  }

});
```
