### ISSUE TITLE
exposing ``isOpen`` to the template

### ISSUE THREAD

**Issue by ghost** [adopted-ember-addons/ember-collapsible-panel#28]
thanks for the great addon!

I'd love to do something like this:

```handlebars
{{#cp-panel as |p|}}
  {{#p.toggle}}
    <h3>
      Cool title
    </h3>
    {{#if p.isOpen}}
      <i class="fa fa-angle-up"></i>
    {{else}}
      <i class="fa fa-angle-down"></i>
    {{/if}}
  {{/p.toggle}}

  {{#p.body}}
    <p>Something cool to show</p>
  {{/p.body}}
{{/cp-panel}}
```

is there a design reason why the ``isOpen`` isn't exposed like above? or am I doing something really dumb at it is anyway?

thanks for the help

**Comment by samselikoff** [comment]
No - I think we can and should expose this. Would you like to PR it?

**Comment by ghost** [comment]
sure, do you mind pointing me at the code I should look at?

**Comment by samselikoff** [comment]
Yep! Add `isOpen=isOpen` right around [here](https://github.com/tedconf/ember-collapsible-panel/blob/master/addon/components/cp-panel/template.hbs#L4).

Then let's add a single test, something like

```js
test('it exposes isOpen', function(assert) {
  this.render(hbs`
    {{#cp-panel as |p|}}
      {{p.toggle}}
      {{#p.body}}
        {{#if p.isOpen}}
          <p>Hi!</p>
        {{/if}}
      {{/p.body}}
    {{/cp-panel}}
  `);

  var $panel = this.$('.cp-Panel');
  // click it
  $panel.find('.cp-Panel-toggle').click();

  assert.ok($panel.find(':contains(Hi!)').length);

});
```

**Comment by samselikoff** [comment]
#29 closes

**Comment by dirkdirk** [comment]
@shicholas Check this out ... this is cool!

This is possible:

```javascript
<i class="fa {{if p.isOpen 'fa-angle-up' 'fa-angle-down'"></i>
```

If you use ember-font-awsome
```javascript
{{fa-icon (if p.isOpen 'angle-up' 'angle-down')}}
```

And if you use ember-paper
```javascript
{{paper-icon (if p.isOpen 'keyboard-arrow-up' 'keyboard-arrow-down')}}
```

**Comment by jbailey4** [comment]
@samselikoff Will this `isOpen` public api be in a release soon?
