### ISSUE TITLE
LiquidFire animations breaking css of some elements

### ISSUE THREAD

**Issue by CourtneyJooste** [adopted-ember-addons/ember-collapsible-panel#34]
Easier to show:
http://tedconf.github.io/ember-collapsible-panel/
Go to the "Nested panels" section, toggle the parent element once or twice and the child elements will display strangely.
Without animations, this issue doesn't happen.

**Comment by samselikoff** [comment]
@CourtneyJooste I believe this is because Liquid Fire's default crossFade transition isn't cancelable.

I would love it if someone could write a cancelable transition that we could include in this library!

**Comment by MelSumner** [comment]
I'm going to close this issue merely due to age. If it's still an issue, please re-open. Thank you! 👍
