### ISSUE TITLE
ember-collapsible-panel may need an ember-cli-version-checker major version bump

### ISSUE THREAD

**Issue by lupestro** [adopted-ember-addons/ember-collapsible-panel#38]
With Ember-CLI 2.18.2, I'm getting the following deprecation message at the start of an `ember serve`:
```
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   new NPMDependencyVersionChecker (C:\Users\rmack\Code\TFS\filterwizard\trunk\source\FilterWizardClient\node_modules\ember-collapsible-panel\node_modules\ember-cli-version-checker\src\npm-dependency-version-checker.js:11:33)
```
The root of the problem is:
```
ember-collapsible-panel@^2.1.1:
  version "2.1.1"
  resolved "https://registry.yarnpkg.com/ember-collapsible-panel/-/ember-collapsible-panel-2.1.1.tgz#2ab8b564f221a284079bd2a049a5f8f29b3fef44"
  dependencies:
    ember-cli-babel "^5.1.6"
    ember-cli-htmlbars "^1.0.3"
    ember-cli-version-checker "^1.1.6" 
```
The latest ember-cli-version-checker is 2.1.0, a major version bump above 1.1.6 (or 1.3.0 or ...), a bit further than I wanted to tweak up in the yarn.lock, since semver promises the possibility of breaking changes.

**Comment by tamzinblake** [comment]
Notice that fixing this will also require upgrading ember-cli-babel and ember-cli-htmlbars which have ember-cli-version-checker as a dependency.

**Comment by mansona** [comment]
I think this is all fixed now that `main` is tested right through to ember-canary 👍 let me know if you have any more issues and I can re-open this
