### ISSUE TITLE
Support for a min-height

### ISSUE THREAD

**Issue by ghost** [adopted-ember-addons/ember-collapsible-panel#4]
I was wondering if you'd be interested in supporting a `min-height` setting? Instead of completely closed and completely open, it would not collapse further than the `min-height` if that property's been set.

So for example:

``` html
{{#cp-panel is-open=true min-height=50px}}
```

**Comment by samselikoff** [comment]
I think you could achieve this by overriding the template for `cp-panel-body`. Check the template out [here](https://github.com/tedconf/ember-collapsible-panel/blob/master/app/templates/components/cp-panel-body.hbs), and just write your own, using {{else}} to `{{yield}}` in a new element with class, and set your `min-height` on that element.

Let me know if that works, and if not we'll reopen. Thanks!

**Comment by ghost** [comment]
Ok, but wouldn't the body content only be rendered when the panel is open? A min-height would require it to be rendered when it's closed as well.

**Comment by samselikoff** [comment]
That's correct, so the current template is

``` hbs
{{#if isOpen}}
  <div class="cp-Panel-body-inner">
    {{yield}}
  </div>
{{/if}}
```

You'd want your template to look like

``` hbs
{{!-- app/templates/cp-panel-body.hbs in your project --}}
{{#if isOpen}}
  <div class="cp-Panel-body-inner">
    {{yield}}
  </div>
{{else}}
  <div class="cp-Panel-body-inner" style="min-height: {{min-height}}">
    {{yield}}
  </div>
{{/if}}
```

Something like this, anyway. Does that make sense?

**Comment by ghost** [comment]
I understand how I'd override the template if this were one of my own components. But I don't see how I can override one of your addons templates? I might be misunderstanding, but after installing the addon, I wouldn't find its templates in my `app` folder, they be somewhere in `node_modules` right?

**Comment by samselikoff** [comment]
Nope if you just create a template for a component named `cp-panel-body` it will prefer that. That's how ember cli's resolver works, when you render `{{cp-panel-body}}` Ember CLI will first look for that template in your application dir, then up the addon chain.

It makes extending addon components super easy. Try it out!

**Comment by ghost** [comment]
Dude, I had no idea. Thanks, I'll try that!

**Comment by samselikoff** [comment]
Closing for now, let me know if you need more help!
