### ISSUE TITLE
Could not find module `@ember/object` imported from `<app>/services/dependency-checker`

### ISSUE THREAD

**Issue by aandis** [adopted-ember-addons/ember-collapsible-panel#41]
Hitting this right after installing. Here's what I have

```
    "ember-cli": "2.6.2",
    "ember-cli-babel": "^5.1.6",
    "ember-cli-dependency-checker": "^1.2.0",
    "ember-collapsible-panel": "3.0.0",
```

Any help?

**Comment by aandis** [comment]
Reverting to `2.1.1` fixes the issue.

**Comment by samselikoff** [comment]
Sorry you ran into this! 3x works with newer versions of Ember that support the new import syntax.

**Comment by aandis** [comment]
@samselikoff some documentation for that would be great. ;)

**Comment by samselikoff** [comment]
Yes - updated the Releases but I should put it on the README. 👍

**Comment by samselikoff** [comment]
https://github.com/tedconf/ember-collapsible-panel/commit/5b590df791e5cb8de9a0b8862d01543cbad6001e

**Comment by samselikoff** [comment]
Turns out addons can use the new import syntax and support older Ember apps as long as their app folders just re-export code under `/addon`. Going to push a commit and let's see if you can use it @aandis

**Comment by samselikoff** [comment]
@aandis could you try `tedconf/ember-collapsible-panel#addon-only-reexport` in your `package.json` and see if it works?

**Comment by aandis** [comment]
@samselikoff works great. Thank you!

**Comment by samselikoff** [comment]
Sweet!

**Comment by samselikoff** [comment]
Published https://github.com/tedconf/ember-collapsible-panel/releases/tag/v3.0.1
