### ISSUE TITLE
Multiple panels open simultaenously

### ISSUE THREAD

**Issue by aandis** [adopted-ember-addons/ember-collapsible-panel#45]
How do I have multiple `panel` open at the same time? Currently opening one `panel` closes the other one.

**Comment by samselikoff** [comment]
The parent cp-panels controls the accordion behavior, but you can just render sibling cp-panel components that don’t share any state.

**Comment by aandis** [comment]
Looking at the [source](https://github.com/tedconf/ember-collapsible-panel/blob/922d971c83291c0864725fd4c2de0e56ec8529c4/addon/services/panel-actions.js#L73), not passing `accordion=true` does what I want. Thanks!
