### ISSUE TITLE
Uncaught Error: unreachable

### ISSUE THREAD

**Issue by noslouch** [adopted-ember-addons/ember-collapsible-panel#47]
Not really sure what's going on, but in a fresh ember app, I'm getting the following error:
![image](https://user-images.githubusercontent.com/2090382/43863875-ff3c103a-9b2b-11e8-9bf1-e7678986f0f8.png)

my project is simply:
```bash
$ ember -v
ember-cli: 3.3.0
node: 8.11.3
os: darwin x64

$ ember new scratch
...

$ cd scratch
$ ember install ember-collapsible-panel
...
[replace application.hbs with "basic usage" example from the docs site]
```

I can give you a repo if you like. I have a hunch it has to do with the module unification/pod component structure.

**Comment by iand675** [comment]
@noslouch replace all block uses of `|p|` with `|panel|` and you should be good to go.

**Comment by ef4** [comment]
Yeah, the gotcha here is caused by angle bracket invocation in Ember.

When you say this:

```hbs
{{#cp-panel as |p|}}
  {{#p.toggle}}
    <p>Click me!</p>
  {{/p.toggle}}
```

The `<p>` tags are actually trying to invoke the `p` variable as if it was a component!

If you're using the default ember-cli-template-lint, it will warn you about this problem.
