### ISSUE TITLE
Add action `didToggle`

### ISSUE THREAD

**Issue by samselikoff** [adopted-ember-addons/ember-collapsible-panel#5]

**Comment by RVenkatesh** [comment]
Any updates on this issue?

**Comment by samselikoff** [comment]
I'm not actively working on this lib anymore but will merge a PR with this feature!

**Comment by jbailey4** [comment]
@RVenkatesh There is now a PR (#44) for this with the last bit of work just pushed up, keep a check on that for updates.

**Comment by samselikoff** [comment]
Published in https://github.com/tedconf/ember-collapsible-panel/releases/tag/v3.1.1
