### ISSUE TITLE
Transfer repo?

### ISSUE THREAD

**Issue by samselikoff** [adopted-ember-addons/ember-collapsible-panel#52]
Hello former colleagues!

I've been half-maintaining this repo since leaving TED, and was thinking it'd be much easier to keep up-to-date with our modern best practices/Travis setups/etc. if we were to transfer it to our EmberMap Github org, where I would have full access to it.

What do you think? We'll take it off of your hands, and of course make sure it still serves all the original use cases if it happens to still be in use at TED!

If this sounds good let's chat next steps :) 

/cc @VinSpee

**Comment by VinSpee** [comment]
Done and done. Thanks!

**Comment by samselikoff** [comment]
Thank you my dude 👊
