### ISSUE TITLE
first item open=true

### ISSUE THREAD

**Issue by ggalli** [adopted-ember-addons/ember-collapsible-panel#55]
I have a code that generate a new panels.panel inside a #each helper and i want to make only first panel with open=true. There's a way to do this?

**Comment by samselikoff** [comment]
`{{each}}` yields an index as the second param, so you could do this:

```hbs
{{#each items as |item index|}}
  {{#cp-panel open=(eq (index 0)) as |panel|}}
    ...
  {{/cp-panel}}
{{/each}}
```

**Comment by samselikoff** [comment]
Let me know if you have any follow-up questions!

**Comment by ggalli** [comment]
I already knew the index as second param, but i tested this code and return me an error: "eq is not a helper". I didn't understand

**Comment by samselikoff** [comment]
Woops worry - try installing the ember-truth-helpers addon

**Comment by ggalli** [comment]
Ok, now i'm getting the following error: "index is not a helper". My code is like this:

`{{#cp-panels accordion=true as |panels|}}
            <div data-test-cp-panel-head class="cp-Panel-head">
                <h3 data-test-cp-panel-title>Serviços</h3>
                <h3 data-test-cp-panel-total>Total</h3>
            </div>
                {{#each model.Services as |service index|}}
                    {{#panels.panel open=(eq (index 0)) as |panel|}}
                        {{#panel.toggle}}
                            <p data-test-service-id><span class="arrow">&#10095;</span> &nbsp;{{t 
                            service.ServiceId}}</p>
                            <p data-test-service-ok>{{format-number service.Totals.OK}}</p>
                        {{/panel.toggle}}
                        {{#panel.body}}
                            {{#each service.Actions as |action|}}
                                <div class="tab-content" data-test-tab-content>
                                    <p data-test-action-id>{{t action.ActionId}}</p>
                                    <p data-test-action-total-ok>{{format-number action.Totals.OK}}</p>
                                </div>
                            {{/each}}
                        {{/panel.body}}
                    {{/panels.panel}}
                {{/each}}
        {{/cp-panels}}`

**Comment by ggalli** [comment]
Ok, now i'm getting the following error: "index is not a helper". My code is like this:

```hbs
{{#cp-panels accordion=true as |panels|}}
            <div data-test-cp-panel-head class="cp-Panel-head">
                <h3 data-test-cp-panel-title>Serviços</h3>
                <h3 data-test-cp-panel-total>Total</h3>
            </div>
                {{#each model.Services as |service index|}}
                    {{#panels.panel open=(eq (index 0)) as |panel|}}
                        {{#panel.toggle}}
                            <p data-test-service-id><span class="arrow">&#10095;</span> &nbsp;{{t service.ServiceId}}</p>
                            <p data-test-service-ok>{{format-number service.Totals.OK}}</p>
                        {{/panel.toggle}}
                        {{#panel.body}}
                            {{#each service.Actions as |action|}}
                                <div class="tab-content" data-test-tab-content>
                                    <p data-test-action-id>{{t action.ActionId}}</p>
                                    <p data-test-action-total-ok>{{format-number action.Totals.OK}}</p>
                                </div>
                            {{/each}}
                        {{/panel.body}}
                    {{/panels.panel}}
                {{/each}}
        {{/cp-panels}}
```

**Comment by samselikoff** [comment]
Try `(eq index 0)` (no extra parens)

**Comment by ggalli** [comment]
It worked! Thanks for your time Sam.
