### ISSUE TITLE
Latest version 3.2.1 is not on npm

### ISSUE THREAD

**Issue by patocallaghan** [adopted-ember-addons/ember-collapsible-panel#57]
It appears the latest tagged version, 3.2.1, is not on npm. I tried install it but it said the latest version is 3.2.0. The npm UI says similar.

![image](https://user-images.githubusercontent.com/685034/52197465-86c78800-2857-11e9-84aa-e22282f8cb44.png)

**Comment by samselikoff** [comment]
Thanks, fixed!

It's confusing too because that tag is `3.2.1` instead of `v3.2.1`... I need to get the travis infra working on this repo.

**Comment by patocallaghan** [comment]
Awesome, thanks 🙌
