### ISSUE TITLE
Public API for panel state

### ISSUE THREAD

**Issue by brenna** [adopted-ember-addons/ember-collapsible-panel#7]
use case: detecting if any panels in a group have been opened (for conditionally displaying a "collapse all" button)

options:
1.  `isAnyOpen(groupName)` - boolean flag specific to this use case
2. `getPanelStates(groupName)` - expose an array of state data (probably just panel name and `isOpen`) and let consumer compute a flag. This could accommodate additional use cases, but also exposes more data publicly.
cc @ryanto @samselikoff

**Comment by msalahz** [comment]
any updates about that? I need to know if panel is open or not in my template?

**Comment by dirkdirk** [comment]
[See Issue #28](https://github.com/tedconf/ember-collapsible-panel/issues/28)

Edit `node_modules/ember-collapsible-panel/addon/components/cp-panel/template.hbs` like [this](https://github.com/tedconf/ember-collapsible-panel/blob/master/addon/components/cp-panel/template.hbs#L4).
