### ISSUE TITLE
override tagname for all elements

### ISSUE THREAD

**Issue by anitricks** [adopted-ember-addons/ember-collapsible-panel#70]
I want to override all the tagNames for creating an expandable table, so I need to override the panel body, the root element's tagname too, etc. Is it possible?

**Comment by MelSumner** [comment]
This addon should not support doing that because a table is not an element that is eligible for interactivity (please see the HTML spec for more details). 

I'm closing this as a stale issue, please re-open if you feel as though it was closed in error. 👍
